### ISSUE TITLE
Symbol Representation

### ISSUE THREAD

**Issue by jwood36** [FuzzyPickles92/Tic_Tac_Toe#2]
The Interface does not show a symbol representation for Player 1 or Player 2

**Comment by FuzzyPickles92** [comment]
In this updated version, the player variable has been renamed to currentPlayer to make its purpose clearer. The player1Symbol and player2Symbol variables have been introduced to hold the symbols used by Player 1 and Player 2, respectively. These variables are displayed in the introductory messages at the beginning of the game and are used throughout the program to indicate which player's turn it is and which symbol each player is using.
